### ISSUE TITLE
Singular Methods For Sending Data

### ISSUE THREAD

**Issue by sohank1** [Cool-Bot-List/Cool-Bot-List-API#2]
### Remember to create the branches.
| Branch | Description |
| ----------- | ----------- |
| total-guilds-method| A method to just send the guilds|
| total-members-method  | A method to just send the members|
| presence-method  |A method to just send the presence|
### When u add the jsdoc. Add it in the jsdoc branch.
# What we have done
- [x] **total-guilds-method** (@aspectiscool)
- [x] **total-members-method** (@CreeperPlanet26)
- [x] **presence-method** (@CreeperPlanet26)

**Comment by Humorist7475** [comment]
ill do guilds!!!!

**Comment by sohank1** [comment]
I will be starting presence rn

**Comment by CreeperPlanet26** [comment]
@aspectiscool put good?

**Comment by sohank1** [comment]
I have finished presenceMethod(). All u need to do now is total-members-method and or total-guilds-method @aspectiscool
